In [1]:
#Import the required library
import numpy as np

In [2]:
#array's
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [3]:
type(a)

numpy.ndarray

In [4]:
#arrange
b=np.arange(10)

In [5]:
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
b=np.arange(1,10,2)

In [7]:
print(b)

[1 3 5 7 9]


In [8]:
#Creating arrays
#1-D array
a=np.array([1,2,3,4,5])

In [9]:
print(a)

[1 2 3 4 5]


In [10]:
#Dimensions
print(a.ndim)

1


In [11]:
#shape
a.shape

(5,)

In [12]:
len(a)

5

In [13]:
#2-D,3-D
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [14]:
type(b)

numpy.ndarray

In [15]:
b.ndim

2

In [16]:
b.shape

(2, 4)

In [17]:
len(b)

2

In [18]:
c=np.array([[[1,2],[3,4]],[[5,6],[8,9]]])

In [19]:
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [8 9]]]


In [20]:
c.ndim

3

In [21]:
c.shape

(2, 2, 2)

In [22]:
len(c)

2

In [23]:
#Fuctions of creating arrays
a=np.arange(10)

In [24]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [25]:
b=np.arange(1,50,5)

In [26]:
print(b)

[ 1  6 11 16 21 26 31 36 41 46]


In [27]:
#using linspace----start,end,num of points
a=np.linspace(0,1,6)

In [28]:
print(a)

[0.  0.2 0.4 0.6 0.8 1. ]


In [29]:
b=np.linspace(1,10,5)
print(b)

[ 1.    3.25  5.5   7.75 10.  ]


In [30]:
c=np.linspace(10,100,20)
print(c)

[ 10.          14.73684211  19.47368421  24.21052632  28.94736842
  33.68421053  38.42105263  43.15789474  47.89473684  52.63157895
  57.36842105  62.10526316  66.84210526  71.57894737  76.31578947
  81.05263158  85.78947368  90.52631579  95.26315789 100.        ]


In [31]:
#common arrays-----output float
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [32]:
b=np.ones((5,5))
print(b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [33]:
b=np.zeros((3,3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [34]:
c=np.zeros((5,5))
print(c)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [35]:
d=np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [36]:
c=np.eye(6)
print(c)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [37]:
d=np.eye(3,4)
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [38]:
f=np.eye(5,6)
print(f)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]]


In [39]:
#creating array using diag function
a=np.diag([1,2,3,4])

In [40]:
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [41]:
type(a)

numpy.ndarray

In [42]:
b=np.diag([5,6,7,7,8])
print(b)

[[5 0 0 0 0]
 [0 6 0 0 0]
 [0 0 7 0 0]
 [0 0 0 7 0]
 [0 0 0 0 8]]


In [43]:
#extract diagnol
a=[1,2,3,4]
np.diag(a)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [44]:
d=[7,7,8,9,9,9,10,11]
print(np.diag(d))

[[ 7  0  0  0  0  0  0  0]
 [ 0  7  0  0  0  0  0  0]
 [ 0  0  8  0  0  0  0  0]
 [ 0  0  0  9  0  0  0  0]
 [ 0  0  0  0  9  0  0  0]
 [ 0  0  0  0  0  9  0  0]
 [ 0  0  0  0  0  0 10  0]
 [ 0  0  0  0  0  0  0 11]]


In [45]:
#create array using random
a=np.random.rand(4)

In [46]:
print(a)

[0.31341004 0.08151131 0.55612087 0.74554694]


In [47]:
d=np.random.rand(10)
print(d)

[0.40915206 0.48473834 0.09671655 0.48463044 0.1636733  0.94751773
 0.91096612 0.49735099 0.0955172  0.82293422]


In [48]:
#Basic data type
a=np.arange(10)
print(a)
print(a.dtype)

[0 1 2 3 4 5 6 7 8 9]
int32


In [49]:
a=np.arange(10,dtype='float64')

In [50]:
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [51]:
a.dtype

dtype('float64')

In [52]:
d=np.array([1+2j,2+6j])

In [53]:
print(d)

[1.+2.j 2.+6.j]


In [54]:
d.dtype

dtype('complex128')

In [55]:
c=np.arange(1,20,3,dtype='complex128')

In [56]:
print(c)

[ 1.+0.j  4.+0.j  7.+0.j 10.+0.j 13.+0.j 16.+0.j 19.+0.j]


In [57]:
d=np.array([1+3j,"World"])

In [58]:
print(d)

['(1+3j)' 'World']


In [59]:
d.dtype

dtype('<U64')

In [60]:
b=np.array([True,False,False,True,True])
print(b)
b.dtype

[ True False False  True  True]


dtype('bool')

In [61]:
#Indexing and slicing
#Indexing---slicing
a=[1,2,3,4,5]
print(a[4])

5


In [62]:
a[:2]

[1, 2]

In [63]:
b=[1,2,3,4,"Hello! World",1+2j,"Hello",90.90,89.90,123]
print(b)

[1, 2, 3, 4, 'Hello! World', (1+2j), 'Hello', 90.9, 89.9, 123]


In [64]:
b[:9]

[1, 2, 3, 4, 'Hello! World', (1+2j), 'Hello', 90.9, 89.9]

In [65]:
b[4]

'Hello! World'

In [66]:
b[::7]

[1, 90.9]

In [67]:
b[-1]

123

In [68]:
#For multidimensional arrays, indexes are tuples of integers
a=np.diag([1,2,3,4])
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [69]:
print(a[2,2])

3


In [70]:
print(a[1,3])

0


In [71]:
print(a[3,3])

4


In [72]:
#Assigning value
a[3,3]=100

In [73]:
print(a)

[[  1   0   0   0]
 [  0   2   0   0]
 [  0   0   3   0]
 [  0   0   0 100]]


In [74]:
a[2,2]=5.02
print(a)

[[  1   0   0   0]
 [  0   2   0   0]
 [  0   0   5   0]
 [  0   0   0 100]]


In [75]:
#copies and views
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [76]:
b=a[::2]

In [77]:
print(b)

[0 2 4 6 8]


In [78]:
b[0]=100

In [79]:
print(b)

[100   2   4   6   8]


In [80]:
#Even we modified 'b', it updated 'a' because both shares same memory
a

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [83]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [84]:
c=a.copy()

In [85]:
print(c)

[0 1 2 3 4 5 6 7 8 9]


In [86]:
a=np.random.randint(0,20,5)

In [87]:
print(a)

[13  2 12 16 13]


In [88]:
b=np.random.randint(1,100,20)

In [89]:
print(b)

[76 66 43 90 92 38 71 39 56 78 65 56 46 83 81 83  2 14 77 15]


In [90]:
#Element wise operations
#Basic operations with scaler
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [91]:
a+1

array([2, 3, 4, 5])

In [92]:
a+34

array([35, 36, 37, 38])

In [93]:
a*24

array([24, 48, 72, 96])

In [94]:
a

array([1, 2, 3, 4])

In [95]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [96]:
a-56

array([-55, -54, -53, -52])

In [97]:
#All arthimetic operations element wise
b=np.ones((3,3))

In [98]:
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [99]:
c=np.ones(4)+1

In [100]:
print(c)

[2. 2. 2. 2.]


In [101]:
d=np.zeros(3)+1

In [102]:
print(d)

[1. 1. 1.]


In [103]:
f=np.ones((3,3))+1

In [104]:
print(f)

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [105]:
print(a)
print(c)

[1 2 3 4]
[2. 2. 2. 2.]


In [106]:
a=np.array([1,2,3,4])
b=np.ones(4)+1

In [107]:
print(a)
print(b)

[1 2 3 4]
[2. 2. 2. 2.]


In [108]:
a+b

array([3., 4., 5., 6.])

In [109]:
a-b

array([-1.,  0.,  1.,  2.])

In [110]:
a**b

array([ 1.,  4.,  9., 16.])

In [111]:
a*b

array([2., 4., 6., 8.])

In [112]:
#Matrix multipication
c=np.diag([1,2,3,4])
print(c)
print('--'*10)
print(c*c)
print('--'*12)
print(c.dot(c))

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
--------------------
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
------------------------
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [113]:
#comparisons
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [114]:
a==b

array([False, False, False, False])

In [115]:
a!=b

array([ True,  True,  True,  True])

In [116]:
a<b

array([ True,  True,  True,  True])

In [117]:
a>b

array([False, False, False, False])

In [118]:
#array wise comparisons
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.array([3,5,7,9])

In [119]:
np.array_equal(a,b)

False

In [120]:
np.array_equal(b,c)

False

In [121]:
np.array_equal(a,c)

False

In [122]:
#Logical operations
a=np.array([1,2,3,4],dtype='bool')
b=np.array([1,2,4,5],dtype='bool')

In [123]:
np.logical_or(a,b)

array([ True,  True,  True,  True])

In [124]:
np.logical_and(a,b)

array([ True,  True,  True,  True])

In [125]:
#Transcendental functions
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [126]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [127]:
np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [128]:
np.cos(a)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [129]:
#shape mismatch
a=np.array(4)

In [131]:
a+np.array([1,2])

array([5, 6])

In [132]:
b=np.array(10)
b+np.array([1,2,3,4])


array([11, 12, 13, 14])

In [133]:
#Bsic reductions
x=np.array([1,2,3,4])
np.sum(x)

10

In [135]:
x=np.array([1,2,3,4])
x.max()

4

In [136]:
x.min()

1

In [139]:
x.argmin()  #Index of minimum element

0

In [140]:
x.argmin() #Index of maximumm element

0

In [141]:
#Logical operations
np.all([True,False,True])

False

In [142]:
np.any([True,False,False,True])

True

In [143]:
#Statistics
x=np.array([1,2,3,4])
y=np.array([5,6,7,8])
print(x)
print(y)

[1 2 3 4]
[5 6 7 8]


In [144]:
x.mean()

2.5

In [145]:
y.mean()

6.5

In [148]:
#Array shape manipulation
a=np.array([[1,2,3],[4,5,6]])

In [149]:
print(a)

[[1 2 3]
 [4 5 6]]


In [150]:
#Flattening
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [154]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [155]:
#Transpose
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [156]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

In [157]:
#Reshaping
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [158]:
print(a.shape)

(2, 4)


In [159]:
b=a.ravel()

In [160]:
print(b)

[1 2 3 4 5 6 7 8]


In [167]:
b=b.reshape(2,4)

In [168]:
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [170]:
b[0,0]=100

In [171]:
print(b)

[[100   2   3   4]
 [  5   6   7   8]]


In [173]:
b[1,2]=70

In [174]:
print(b)

[[100   2   3   4]
 [  5   6  70   8]]


In [175]:
#Dimension shuffling
a=np.arange(4)

In [176]:
print(a)

[0 1 2 3]


In [179]:
a.resize((8,8))

In [180]:
print(a)

[[0 1 2 3 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [181]:
#Sorting data
a=np.random.randint(10,100,20)

In [182]:
print(a)

[73 67 46 85 96 18 76 39 67 79 83 98 32 81 62 79 38 75 86 88]


In [184]:
b=np.sort(a
         )

In [185]:
print(b)

[18 32 38 39 46 62 67 67 73 75 76 79 79 81 83 85 86 88 96 98]
